Add C language code sample for tests
JoaoDanielRufino/gcloc pull request #30
Opened 2022-10-03 02:07 UTC by miles170

Closes #25.

2022-10-03 15:48 UTC, JoaoDanielRufino requested changes
Good work, thanks for creating this PR.

2022-10-03 15:48 UTC, JoaoDanielRufino commented on test/fixtures/code_samples/go.mod
> +// Exclude this directory from go
Could you delete this file ?

2022-10-03 22:46 UTC, JoaoDanielRufino requested changes
The file `test/fixtures/code_samples/go.mod` is still there, could you **DELETE** the file ?

2022-10-04 01:06 UTC, miles170 commented
If I delete `test/fixtures/code_samples/go.mod`, `go list ./...` will throw `package github.com/JoaoDanielRufino/gcloc/test/fixtures/code_samples: C source files not allowed when not using cgo or SWIG: main.c`

2022-10-04 13:12 UTC, JoaoDanielRufino approved these changes
Good work!

2022-10-04 13:13 UTC, merged