Add ruby code sample for test (#40)
JoaoDanielRufino/gcloc pull request #45
Opened 2022-10-07 08:25 UTC by ChandanChainani

Fixes #40

2022-10-07 13:12 UTC, JoaoDanielRufino requested changes

2022-10-07 19:09 UTC, ChandanChainani commented
@JoaoDanielRufino

Few cases which are currently not working for ruby code:
- line with code and comment together
 ```
 puts "Welcome to Ruby!"     # prints the welcome message
 ```
- other form of comment that is allowed in ruby
  ```
  =begin
  This is a comment line
  it explains that the next line of code displays
  a welcome message
  =end
  ```

2022-10-07 20:25 UTC, JoaoDanielRufino commented
> @JoaoDanielRufino
> 
> Few cases which are currently not working for ruby code:
> 
> * line with code and comment together
> 
> ```
> puts "Welcome to Ruby!"     # prints the welcome message
> ```
> 
> * Other form of comment that is allowed in ruby
>   ```
>   =begin
>   This is a comment line
>   it explains that the next line of code displays
>   a welcome message
>   =end
>   ```
@ChandanChainani 

The line with code and comment together should not be counted as a comment line, so the code is working properly.

The block comment is supported by gcloc, could you add it on the code ? I think you didn't understand my review when I asked for it

2022-10-07 20:26 UTC, JoaoDanielRufino requested changes

2022-10-07 20:26 UTC, JoaoDanielRufino commented on test/fixtures/code_samples/main.rb
> +# Segregate 0s on left side and 1s on right side of the array
Could you convert this to a block comment ?
```suggestion
=begin
Given an array of 0s and 1s in random order.
Segregate 0s on left side and 1s on right side of the array
=end
```

2022-10-09 01:25 UTC, JoaoDanielRufino approved these changes
Thanks for the amazing contribution!

2022-10-09 01:27 UTC, merged